modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/noobanidus/Bigger-Rabbit-Hitboxes/issues" #optional
license="https://github.com/noobanidus/bigger-rabbit-hitboxes/blob/master/LICENSE"
[[mods]]
modId="brh"
version="${file.jarVersion}"
displayName="Bigger Rabbit Hitboxes"
displayURL="https://minecraft.curseforge.com/projects/bigger-rabbit-hitboxes"
authors="Noobanidus"
description='''
Makes Rabbit and Silverfish Hitboxes bigger, so they're easier to hit!
'''
[[dependencies.brh]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.brh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
